### ISSUE TITLE
[Backend] Writing custom User model

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#1]
우리가 사용하는 User 모델이 Django의 디폴트 User 모델에 필드를 추가한 형태인데,

아예 새로운 User 모델을 만들기보다는 OneToOne relation을 활용하는 형태로 디자인하는게 어떨까요. ([참고](https://wikidocs.net/6651))

이렇게 하면 기존 django의 인증 함수들을 그대로 사용할 수 있습니다.

**Comment by ddoyoon** [comment]
참고 걸어주신 링크를 확인해봤는데, 저희가 계획한대로 User 모델을 구현하기에 적합한 방식인 것 같습니다.

**Comment by ryanking13** [comment]
https://github.com/SNUWagon/SNUwagon-back/blob/af1ac89be66969f56dfc38787046581a318f4196/api/models.py#L6-L9

`Profile` 로 이름 변경하고 User model과 연결했습니다
