### ISSUE TITLE
[Backend] API specification

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#13]
drf-yasg 이용해서 request / response 파라미터에 대한 정보를 작성할 수 있기는 한데,

파라미터를 serializer로 입력하다보니 필요없는 값이 좀 추가됩니다.
 
예를들어 sign in api 의 경우는 username과 password만 파라미터로 넘기면 되는데, UserSerializer를 사용할 경우에는 email 항목까지 표시되어 헷갈릴 수가 있습니다.

API 별로 serializer를 만들어 사용하는 것이 한 방법이 될 것 같은데 이건 다소 불필요한 부하가 큰 것 같다고 생각되네요.

그래서 우선은 Markdown형태로 간이 API spec 문서를 작성하는 것이 어떨까요.

**Comment by ryanking13** [comment]
아래와 같이 작성하면 될 것 같습니다.

## Sign in

### Request

    POST /api/auth/signin

parameter:

| Parameter | Description      | Example |
| --------- | ---------------- | ------- |
| username   | username          | testuser     |
| password     | password        | testpassword       |

### Response

On success:

    {
      "success": true,
      "message": ''
    }

On fail:

    # on wrong username or password
    {
      "success": false,
      "message": "Wrong username of password"
    }

**Comment by kjp4155** [comment]
@leejisup 일단 이번 iteration에서 급한 signin&signup 이랑 question, information 부분부터 먼저 해주세요
