### ISSUE TITLE
[Frontend] Handling error response

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#19]
ARc의 기본 api.request() 함수는 response의 status가 2xx이 아니면 에러를 던지도록 되어있는데,

[#11]에서 논의한 대로 API의 성공/실패 판정을 success값으로 정하기로 했기 때문에  status를 무시하고 진행되도록 했어요. (브라우저 디버그 콘솔 상에는 표시됩니다)

따라서 구현하는 쪽에서는, try~catch가 아니라 success값에 따른 분기를 만들어주어야 합니다.

```js
// 기존
try {
  const response = api.get('url')
} catch {
  // error handling
}

handleResponse(response)
```

```js
// 변화
const response = api.get('url')

if (response.success === true) {
  handleResponse(response)
} else {
  // error handling
}
```

**Comment by ryanking13** [comment]
적절한 방식인가에 대하여 논의할 것이 있으면 코멘트 달아주세요

**Comment by ddoyoon** [comment]
저희가 사용하기로 한 response format에 적절한 방식인 것 같습니다. user 부분에서 이 방식대로 구현하신 것도 확인했습니다.
