### ISSUE TITLE
[Frontend] Design modification regarding QuestionAnswerWrite

### ISSUE THREAD

**Issue by ddoyoon** [SNUWagon/SNUwagon-back#20]
현재 디자인에서는 Question에서 Answer 버튼을 누르면 답변을 작성하는 페이지로 redirect 후 그 페이지에서 답변을 달게 되어있는데, Question 내용을 보면서 답변 내용을 작성하는 것이 더 자연스럽다고 느껴집니다.
따로 답변을 다는 페이지를 만들지 않고 Question 하단에 답변을 작성하는 text field와 submit 버튼을 추가하는 방식으로 디자인을 수정하는 것이 어떨까요? 더 나은 아이디어가 있다면 코멘트 남겨주세요.

**Comment by kjp4155** [comment]
예 그냥 form하나만 밑에 보여지게 하면 될거같아요

버튼을 눌러야만 표시되는 기능은 일단 하지말고 나중에 하든지 하죠

**Comment by ryanking13** [comment]
네 github issue처럼 답변 달 수 있는 창이 바로 보이게 하는 게 좋아보이네요
