### ISSUE TITLE
[Backend] Answer을 쓰는 기능에 관한 API 추가가 필요할 것 같습니다.

### ISSUE THREAD

**Issue by leejisup** [SNUWagon/SNUwagon-back#21]
SWPP_SNUwagon_Design_and_Planning 문서의 Backend API Table에서 Answer을 쓰는 기능에 대한 부분을 추가해야 할 것 같습니다.

**Comment by ryanking13** [comment]
스펙 짤 때 빠트렸네요.

URL은 이렇게 하면 되려나요

```
POST /api/posts/answer
```

**Comment by kjp4155** [comment]
그럽시다
