### ISSUE TITLE
[Backend] [TODO] question, information POST시 없는 user이면 에러 처리

### ISSUE THREAD

**Issue by kjp4155** [SNUWagon/SNUwagon-back#25]
[Backend] [TODO] question, information POST시 없는 user이면 에러 처리

**Comment by ryanking13** [comment]
나중에는 authenticated user만 접근 가능하다는 걸 이용해서 그냥 request.user를 사용하는 식으로 바꾸는 걸 생각해보죠

**Comment by ryanking13** [comment]
@kjp4155 이거 아직 해결 안 됐나여

**Comment by kjp4155** [comment]
프론트에서 잘 걸러주던데요
