### ISSUE TITLE
[Frontend] About using material UI

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#27]
UI 디자인을 [Material UI](https://www.material-ui.com/)로 하면 어떨까요.

리액트와 가장 호환성이 좋습니다.

단점은 아직 styled-components 와의 호환성이 없어서 이것들을 덜어내야 합니다.

**Comment by kjp4155** [comment]
근데 그럼 디자인 다시 하나요?

**Comment by ryanking13** [comment]
기존에 작성한 UI 컴포넌트들은 일단 두고 여유가 될 때 바꾸는 걸로 합시다

**Comment by kjp4155** [comment]
지금 document들에 들어있는 디자인은 일단 무시하나요 그럼

**Comment by kjp4155** [comment]
close는 잘못 눌렀네요

**Comment by ryanking13** [comment]
document에 있는 디자인은 어차피 스케치니까 어떤 것으로 구현하던 크게 상관 없을 것 같아요
