### ISSUE TITLE
[Backend] Author in Question details

### ISSUE THREAD

**Issue by ddoyoon** [SNUWagon/SNUwagon-back#36]
GET /posts/question/{id}에서 id에 해당하는 질문의 내용을 가져올 때 response.data.author는 작성자의 id입니다.
그러나 사용자들은 자신의 id를 모르기 때문에 작성자의 id가 아닌 username을 보여주는 것이 더 직관적이라고 생각합니다. 다른 분들의 의견이 궁금합니다!

**Comment by kjp4155** [comment]
그렇게 되도록 백엔드 response를 수정했습니다
