### ISSUE TITLE
[Backend] Changing API management tool

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#4]
지금 REST API 관리용으로 [django-rest-swagger](https://github.com/marcgibbons/django-rest-swagger) 를 쓰고 있는데, django-rest-framework가 3.6 부터 API를 coreapi로 바꾸면서 많은 부분이 변경되었는데 아직 지원이 완벽하지 않습니다.

특히 yaml parsing이 deprecated 되어서 function based view의 파라미터를 작성하기에 어려움이 따릅니다.

그래서 API 관리 툴을 django-rest-framework 최신 버전과 잘 들어맞는 [drf-yasg](https://github.com/axnsan12/drf-yasg)로 바꾸는 게 어떨까 싶네요.

**Comment by kjp4155** [comment]
예 그럽시다
