### ISSUE TITLE
[Overall] Answer관련 API 추가 요청

### ISSUE THREAD

**Issue by kjp4155** [SNUWagon/SNUwagon-back#40]
현재 특정 question에 대한 답변을 채택하는 기능을 위한 API가 없습니다.
또한 답변과 관련된 API들이 많이 부족합니다.

따라서 다음과 같은 API들 추가를 요청합니다.

[POST] /api/posts/answer/
특정question id에 해당하는 question에 답변을 등록하는 api입니다.
request body에 question id와 함께 답변 내용을 넣어서 전달합니다.
{
  "question_id": 3,
  "username": David,
  "content": Sampletext
}

와 같은 request형식을 가집니다.

[POST] /api/posts/selectanswer/
특정 question 에서 질문자가 답변을 채택하는 api입니다.
request body에 question id와 answer id를 함께 넣어서 전달합니다.
{
  "question_id": 3,
  "answer_id": 6
}
와 같은 request형식을 가집니다.

**Comment by ryanking13** [comment]
다음에 API 다듬으면서 같이 논의하죠
