### ISSUE TITLE
[Backend] 코드 질문

### ISSUE THREAD

**Issue by kjp4155** [SNUWagon/SNUwagon-back#5]
https://github.com/SNUWagon/SNUwagon-back/blob/af1ac89be66969f56dfc38787046581a318f4196/api/views/auth_views.py#L13

데코레이터에 POST밖에 없는데 POST인지 또 체크할필요 있습니까

**Comment by ryanking13** [comment]
일관성이나 확장성을 고려했을 때는 일괄적으로 다는 것이 좋지 않을까 생각해요

**Comment by kjp4155** [comment]
그럽시다
