### ISSUE TITLE
[Backend] Adding tag API

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#50]
검색이나 글 작성할 때 보조용으로 태그 예시를 보여주면 좋을 것 같은데,
태그 목록을 리턴해주는 API가 있으면 유용하게 쓸 수 있을 것 같아요.

    GET /api/list/tags

구현 자체에 꼭 필요한 API는 아니니까 우선순위 급한거 처리하고 천천히 얘기해봅시다.

**Comment by kjp4155** [comment]
구현 했어요

리뷰 하시면 좋고 귀찮으면 믿음으로 머지 하셔도 되고..
