### ISSUE TITLE
[Backend] list api 동작 오류

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#54]
/api/list/questions/title, tag
    /api/list/informations/title, tag

1. author 값이 id로 넘어옵니다. username으로 바꿔주세요.

2. 해당하는 값이 없을 때 지금 아예 data parameter가 안 오는데 empty array가 오게 해주세요.

**Comment by kjp4155** [comment]
#55 리뷰하고 머지해주세영
