### ISSUE TITLE
[Backend] Model attribute naming 문제

### ISSUE THREAD

**Issue by kjp4155** [SNUWagon/SNUwagon-back#6]
Design and Planning document에서 모델을 정의할 때 type이라는 column명이 자주 쓰였는데, 
파이썬의 built-in function인 type과 겹쳐서 안 쓰는게 좋다고 합니다. 
서브라임에서 색칠도 이상해요.

QuestionPost 모델의 type은 question_type
Tag 모델의 type은 tag_type
으로 바꿔서 구현할게요

**Comment by ryanking13** [comment]
category 같은 동의어를 쓰는 방법도 있긴 한데,
category보다는 question_type이 실제 의미 상 더 명확한 것 같으니 좋아 보입니다.
