### ISSUE TITLE
[Backend] Wrong regex on urls.py

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#63]
https://github.com/SNUWagon/SNUwagon-back/blob/455f36cc81c3d927c052ddec5ff4a031b1832aca/api/urls.py#L19

https://github.com/SNUWagon/SNUwagon-back/blob/455f36cc81c3d927c052ddec5ff4a031b1832aca/api/urls.py#L23

regex가 숫자로 되어있어요 고쳐주세요 흑흑

**Comment by ryanking13** [comment]
아직 구현도 안 됐었군요

**Comment by kjp4155** [comment]
예 그래서 눈치못채고 있었음

**Comment by kjp4155** [comment]
고쳤어영. 
확인하고 Close해주세영
