### ISSUE TITLE
[Backend] debug view access restriction

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#86]
debug view들이 debug 환경에서만 접근 가능하게 해주세요.

settings.DEBUG 값이 true일 때만 urlpatterns에 추가하는 식으로 하면 돼요

https://github.com/SNUWagon/SNUwagon-back/blob/593a06c13af4255afda2e6c7d8aaa465d5dfd95d/backend/urls.py#L28

**Comment by kjp4155** [comment]
일단 Debug=False 모드에선 접근은 가능하지만 실제 반영은 안 되도록 구현해놨어요
