### ISSUE TITLE
[Both] Voting system

### ISSUE THREAD

**Issue by ryanking13** [SNUWagon/SNUwagon-back#93]
vote 기능에 필요한 API와 기능을 만듭시다.

- Backend
  - upvote
  - downvote
  - 유저 정보의 vote 값 보여주기
  - (+) vote에 따른 credit 지급/저하?

- Frontend
  - vote 값에 따른 아이디 표시 변경

**Comment by kjp4155** [comment]
이건 회의 한번 하고 만들죠

**Comment by kjp4155** [comment]
일단 가장 기본적인 기능을 구현했습니다 #100
